name: Daily LinkedIn Post

on:
  schedule:
    - cron: '13 11 * * *'  # Runs every day at 12:30 PM UTC = 6:00 PM IST
  workflow_dispatch:       # Optional: allow manual run from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node dailyPoster.js
